# SwiftLint Configuration for Traveling Snails
# Security-focused configuration with modern Swift/SwiftUI patterns

# Files and directories to include/exclude
included:
  - Traveling Snails
  - Traveling Snails Tests

excluded:
  - .build
  - .swiftpm
  - Packages
  - "*/Generated"
  - "*/Resources"
  - "**/*.generated.swift"
  - Traveling Snails.xcodeproj
  - DerivedData

# Analyzer rules (require compilation)
analyzer_rules:
  - explicit_self
  - unused_import
  - unused_declaration

# Opt-in rules (not enabled by default)
opt_in_rules:
  - accessibility_label_for_image
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_enum_raw_value
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - no_extension_access_modifier
  - no_grouping_extension
  - number_separator
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - type_contents_order
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - weak_delegate
  - xct_specific_matcher
  - yoda_condition

# Disabled rules
disabled_rules:
  - todo # Allow TODO comments for development
  - line_length # We'll use a more reasonable line length
  - type_body_length # Some models may be longer
  - file_length # Some files may be longer for comprehensive functionality

# Custom rules for security and project-specific patterns
custom_rules:
  # SECURITY: Prohibit print statements - force use of Logger
  no_print_statements:
    name: "No Print Statements"
    regex: '\bprint\s*\('
    message: "Use Logger.shared instead of print statements for security and consistency"
    severity: error
    
  # SECURITY: Detect potential sensitive data logging
  no_sensitive_logging:
    name: "No Sensitive Data Logging"
    regex: '(trip\.name|\.name.*[Ll]og|[Ll]og.*\.name|user\..*[Ll]og|[Ll]og.*user\.|password|token|secret|key.*[Ll]og|[Ll]og.*key)'
    message: "Potential sensitive data in logging - review for security implications"
    severity: warning
    
  # SECURITY: Ensure proper error handling doesn't expose internals
  safe_error_messages:
    name: "Safe Error Messages"
    regex: '(LocalizedError|Error.*message).*(\binternal\b|\bprivate\b|\bdebug\b|\bstack\b)'
    message: "Error messages should not expose internal implementation details"
    severity: warning
    
  # MODERN SWIFT: Enforce NavigationStack over NavigationView
  use_navigation_stack:
    name: "Use NavigationStack"
    regex: '\bNavigationView\b'
    message: "Use NavigationStack instead of deprecated NavigationView (iOS 16+)"
    severity: error
    
  # MODERN SWIFT: Enforce L10n enum over NSLocalizedString
  use_l10n_enum:
    name: "Use L10n Enum"
    regex: '\bNSLocalizedString\b'
    message: "Use L10n enum system instead of NSLocalizedString for consistency"
    severity: warning
    
  # MODERN SWIFT: Detect hardcoded strings that should be localized
  no_hardcoded_strings:
    name: "No Hardcoded UI Strings"
    regex: '(Text|Label|Button|Alert)\s*\(\s*"[A-Z][a-zA-Z\s]{10,}"'
    message: "UI strings should use L10n enum system for localization"
    severity: warning
    
  # SWIFTDATA: Prevent parameter passing anti-pattern
  no_swiftdata_parameter_passing:
    name: "No SwiftData Parameter Passing"
    regex: '(init|func).*\([^)]*:\s*\[[A-Z][a-zA-Z]*\]\s*[,)]'
    message: "Avoid passing SwiftData model arrays as parameters - use @Query in consuming view instead"
    severity: warning
    
  # MODERN SWIFT: Enforce @Observable over @StateObject
  no_state_object:
    name: "Use @Observable instead of @StateObject"
    regex: '@StateObject|@ObservableObject'
    message: "Use @Observable instead of @StateObject/@ObservableObject (iOS 17+)"
    severity: error
    
  # SECURITY: Enforce input validation patterns
  require_input_validation:
    name: "Input Validation Required"
    regex: '(TextField|TextEditor).*(?!.*\.validate|.*isValid|.*validation)'
    message: "User input fields should include validation"
    severity: warning

# Rule configurations
accessibility_label_for_image:
  severity: warning

array_init:
  severity: warning

attributes:
  always_on_same_line:
    - "@IBAction"
    - "@NSManaged"
    - "@objc"

closure_end_indentation:
  severity: warning

closure_spacing:
  severity: warning

collection_alignment:
  align_colons: true

conditional_returns_on_newline:
  if_only: true

contains_over_filter_count:
  severity: error

contains_over_filter_is_empty:
  severity: error

cyclomatic_complexity:
  warning: 15
  error: 25

empty_count:
  severity: error
  only_after_dot: true

empty_string:
  severity: warning

enum_case_associated_values_count:
  warning: 6
  error: 8

explicit_enum_raw_value:
  severity: warning

file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*\.swift
                    \/\/  Traveling Snails.*
                    \/\/

file_name:
  severity: warning
  excluded:
    - "Generated"
    - "Pods"

file_name_no_space:
  severity: error

function_body_length:
  warning: 100
  error: 200

function_parameter_count:
  warning: 6
  error: 8

identifier_name:
  min_length: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - "id"
    - "URL"
    - "x"
    - "y"
    - "z"

large_tuple:
  warning: 3
  error: 4

line_length:
  warning: 150
  error: 200
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
  ignores_interpolated_strings: true

modifier_order:
  preferred_modifier_order:
    - "override"
    - "acl"
    - "setterACL"
    - "dynamic"
    - "mutating"
    - "lazy"
    - "final"
    - "required"
    - "convenience"
    - "typeMethods"
    - "owned"

multiline_arguments:
  first_argument_location: next_line
  only_enforce_after_first_closure_on_first_line: true

multiline_parameters:
  allows_single_line: true

nesting:
  type_level:
    warning: 2
    error: 3

number_separator:
  minimum_length: 5
  minimum_fraction_length: 5

private_outlet:
  allow_private_set: true

reduce_into:
  severity: error

redundant_nil_coalescing:
  severity: error

sorted_imports:
  severity: warning

trailing_comma:
  mandatory_comma: true

trailing_whitespace:
  ignores_empty_lines: false
  ignores_comments: true

type_body_length:
  warning: 300
  error: 500

type_contents_order:
  order:
    - case
    - associated_type
    - type_alias
    - subtype
    - type_property
    - instance_property
    - ib_outlet
    - ib_inspectable
    - initializer
    - type_method
    - view_life_cycle_method
    - ib_action
    - other_method
    - subscript

type_name:
  min_length: 3
  max_length:
    warning: 50
    error: 60

vertical_whitespace:
  max_empty_lines: 2

warning_threshold: 10